### ISSUE TITLE
Versionsverwaltung

### ISSUE THREAD

**Issue by ElBartscho** [AlexanderNahr/arduino_team_PMES_WS2016#10]
GIT/SVN einrichten und Templateprojekt als Grundlage für alle Projektmitglieder bereitstellen.

Der PO muss in der lage sein das Projekt auschecken und das Template auf den Arduino zu flashen. (z.B. LED Blinkt) Achtet darauf das das Archiv frei von lokalen Abhängigkeiten ist. (Includepfade …) Es Funktioniert dann bei euch, aber bei anderen Teammitglieder nicht. :-(

**Comment by ElBartscho** [comment]
Klasse Idee mit GiT!

PS: Wollte mal sehen was der Kommentar hier bewirkt....

**Comment by AlexanderNahr** [comment]
Jo, laeuft ganz gut! :)
