### ISSUE TITLE
UART HandsOn + Modulplanung UART

### ISSUE THREAD

**Issue by ElBartscho** [AlexanderNahr/arduino_team_PMES_WS2016#16]
Die UART Schnittstelle ist für die Kommunikation zum WLAN Modul verantwortlich.

Der Modulaufbau soll in diesem Arbeitspaket geklärt werden.

- Wie Funktioniert die Schnittstelle?
- Was muss beachtet werden?
- Wie arbeitet das Modul ? (z.B. Interrupt oder polling)
- Wie könnte die Schnittstelle (API) zu diesem Modul aussehen?

Derzeit gehe ich davon aus, dass wir die WLAN empfangenen Strings 1 zu 1 vom WLAN Modul über die UART Schnittstelle weiterleiten. Können wir diesen Ansatz verfolgen oder gibt es noch spezielle Dinge die wir in diesem Zusammenhang bedenken müssen? (String Terminierung oder z.B. spezielle Steuerbefehle die für das WLAN Modul notwendig sind?

- [ ] Modulplanungsdokument
- [ ] PIKESOLUTION: UART Kommunikation mit beliebigen Empfänger ind GIT einchecken.

**Comment by myhamidi** [comment]
Diese Aufgabe sollte mit der Wiki Dokumentation zum WiFly und mit der "SW_UART.ino" (anpingen war möglich) fertig sein.
Was meint ihr?
