### ISSUE TITLE
WiFi Service Klasse

### ISSUE THREAD

**Issue by myhamidi** [AlexanderNahr/arduino_team_PMES_WS2016#76]
In den Modes der Klasse "String Complete" und "Prepare for next String" werden keine Zeichen eingelesen. D. h. wenn zwei String kurz hinter einander gesendet werden (innerhalb ~1s), wird u. U. nur der erste 
String erkannt.

Klärung ob das okay ist, oder ein Problem für die Anwendung darstellt

**Comment by ElBartscho** [comment]
Was ist denn der Grund dafür?  Eine Sekunde ist ja wirklich lange...

**Comment by myhamidi** [comment]
Hab ich gefixt: Commit: c8bd3ce3d14d363b2ca54211c9f1a1e542cfb4fc
